# Generated by Django 6.1.1 on 2026-10-06 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_date', models.DateField(help_text='The chosen date for the invitation')),
                ('selected_time', models.TimeField(help_text='The chosen time for the invitation')),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Latitude of the selected location', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Longitude of the selected location', max_digits=9)),
                ('location_name', models.CharField(blank=True, default='', help_text='Human-readable location name (optional reverse geocode)', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user at submission time (admin only)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Date Request',
                'verbose_name_plural': 'Date Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
